Revert "ANDROID: Enable DWARF CRCs and long symbols for MODVERSIONS"
It's broken right now(?) Getting multiple of such errors:

error: gendwarfksyms: process_module: dwarf_get_units failed: no debugging information?

BTW, note that the package `libdw-dev` needs to be installed to fix dwarf.h missing.

This reverts commit d1d95e850a8c96170b3de5f6b46d9bef7ffe2af1.

Change-Id: I234642ca34e87c2a9994725f48a4f26c36f3406f